export const WATCH_HOLIDAY_LIST = 'WATCH_HOLIDAY_LIST';
export const LIST_LOADING_INITIATE = 'LIST_LOADING_INITIATE';
export const LIST_LOADING_SUCCESS = 'LIST_LOADING_SUCCESS';
export const LIST_LOADING_FAILED = 'LIST_LOADING_FAILED';
